spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentalcar?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  jackson:
    mapper:
      accept-case-insensitive-enums: true

